spring.application.name=Wallet-app

# Ensure MongoDB uses UTC and configuring the mongodb to connect with spring boot application
spring.data.mongodb.uri=mongodb://localhost:27017/Transactions?serverTimeZone=UTC

spring.main.web-application-type=reactive

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.cloud.discovery.enabled=false

# Set timezone to UTC for Jackson (JSON handling)
spring.jackson.time-zone=UTC



server.port=8006
